In [2]:
import numpy as np

In [3]:
A = np.array([[2, 1, 3], [4, -6, -2], [-2, 7, 5]])

In [5]:
b = np.array([1, 1, 0])

In [8]:
U, Sigma, Vt = np.linalg.svd(A)
V = Vt.T

In [21]:
U

array([[ 0.14018727,  0.80437193, -0.57735027],
       [-0.62651289,  0.5235917 ,  0.57735027],
       [ 0.76670016,  0.28078023,  0.57735027]])

In [79]:
Proj = np.empty((U.shape[1], U.shape[1]))

for e in range(U.shape[1]):
    vec = np.empty(U.shape[1])
    basis = np.zeros(U.shape[1])
    basis[e] = 1
    print("basis")
    for i in range(U.shape[1]):
        print("vec >> ", vec)
        print(U[:, i])
        vec = np.add(vec, (U[:, i].T @ basis) * U[:, i])
        print("U >> ", (U[:, i].T @ basis) * U[:, i])
    print("final vec >> ", vec)
    print()
    Proj[:, e] = vec
    
print(Proj)

basis
vec >>  [0.14018727 0.62651289 0.76670016]
[ 0.14018727 -0.62651289  0.76670016]
U >>  [ 0.01965247 -0.08782913  0.1074816 ]
vec >>  [0.15983973 0.53868376 0.87418175]
[0.80437193 0.5235917  0.28078023]
U >>  [0.6470142  0.42116246 0.22585174]
vec >>  [0.80685393 0.95984622 1.10003349]
[-0.57735027  0.57735027  0.57735027]
U >>  [ 0.33333333 -0.33333333 -0.33333333]
final vec >>  [1.14018727 0.62651289 0.76670016]

basis
vec >>  [1.14018727 0.62651289 0.76670016]
[ 0.14018727 -0.62651289  0.76670016]
U >>  [-0.08782913  0.3925184  -0.48034753]
vec >>  [1.05235814 1.01903129 0.28635262]
[0.80437193 0.5235917  0.28078023]
U >>  [0.42116246 0.27414826 0.1470142 ]
vec >>  [1.4735206  1.29317956 0.43336682]
[-0.57735027  0.57735027  0.57735027]
U >>  [-0.33333333  0.33333333  0.33333333]
final vec >>  [1.14018727 1.62651289 0.76670016]

basis
vec >>  [1.14018727 1.62651289 0.76670016]
[ 0.14018727 -0.62651289  0.76670016]
U >>  [ 0.1074816  -0.48034753  0.58782913]
vec >>  [1.24766886

In [80]:
Proj @ b

array([2.28037453, 2.25302578, 1.53340031])

In [81]:
P = U @ np.linalg.inv(U.T @ U) @ U.T
print(P)

[[ 1.00000000e+00  8.42200963e-17  9.28077013e-17]
 [ 1.60891979e-16  1.00000000e+00 -8.42200963e-17]
 [ 2.94613014e-18 -2.87089451e-17  1.00000000e+00]]


In [85]:
b

array([1, 1, 0])

In [84]:
P@b

array([ 1.00000000e+00,  1.00000000e+00, -2.57628149e-17])